import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./global.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";
import { Toaster } from "sonner";
import { StripeNotificationBanner } from "@/components/Stripe/StripeNotificationBanner";
import { getCurrentUser } from "@/actions/getCurrentUser";
import { getTrpcCaller } from "@/trpc";

const jacarta = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getCurrentUser();
  const trpcCaller = await getTrpcCaller();
  const isCoach = !!user?.coachId;

  const coach = isCoach
    ? await trpcCaller.coach.get({
        where: {
          id: user?.coachId,
        },
        select: {
          id: true,
          stripeAccountId: true,
        },
      })
    : undefined;

  return (
    <html lang="en" className="h-full">
      <body className={cn("relative h-full antialiased", jacarta.className)}>
        <main className="relative flex flex-col min-h-screen">
          <Providers>
            {coach && <StripeNotificationBanner coach={coach} />}
            <Navbar />
            <div className="flex-grow flex-1">{children}</div>
          </Providers>
        </main>

        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
